name: CI-src

on:
  workflow_call:

permissions: {}
env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    defaults:
      run:
        shell: bash

    permissions:
      contents: read

    steps:
      - run: cat "$GITHUB_EVENT_PATH"

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          sparse-checkout: |
            src
          sparse-checkout-cone-mode: true

      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: 10.0.301

      - name: Build
        run: dotnet build "src/MySampleConsoleApp1/MySampleConsoleApp1.csproj"
